blog/urls.py
from django.conf.urls import url
from .feeds import LatestPostsFeed
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    #url(r'$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'
        r'(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
     url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
     url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
     url(r'^feed/$', LatestPostsFeed(), name='post_feed'),
      url(r'^search/$', views.post_search, name='post_search'),
]

blog_dz/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf.urls.static import static
from blog.sitemaps import PostSitemap
from django.conf import settings

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor', include('ckeditor_uploader.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG is True:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES=(('draft', 'Draft'), ('published', 'Published'))
    title=models.CharField(max_length=250)
    slug=models.SlugField(max_length=250, unique_for_date='publish')
    author=models.ForeignKey(User, related_name='blog_posts')
    body=RichTextField()
    publish=models.DateTimeField(timezone.now)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    status=models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()
    published = PublishedManager()
    tags=TaggableManager()


    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])

    class Meta:
        ordering=('-publish',)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post=models.ForeignKey(Post, related_name='comments')
    name=models.CharField(max_length=60)
    email=models.EmailField()
    body=models.TextField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    active=models.BooleanField(default=True)

    class Meta:
        ordering=('created',)

    def __str__(self):
        return 'Comment by:  {} on {}.'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name=forms.CharField(max_length=25)
    email=forms.EmailField()
    to=forms.EmailField()
    comments=forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('name', 'email', 'body')

class SearchForm(forms.Form):
    query=forms.CharField()

blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.db.models import Count
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.views.generic import ListView
from haystack.query import SearchQuerySet
from taggit.models import Tag
from .forms import EmailPostForm, CommentForm, SearchForm
from .models import Post, Comment

class PostListView(ListView):
    queryset=Post.published.all()
    context_object_name='posts'
    paginate_by=3
    template_name='blog/post/list.html'

def post_list(request, tag_slug=None):
    object_list=Post.published.all()
    tag=None

    if tag_slug:
        tag=get_object_or_404(Tag, slug=tag_slug)
        object_list=object_list.filter(tags__in=[tag])

    paginator=Paginator(object_list, 3)
    page=request.GET.get('page')

    try:
        posts=paginator.page(page)
    except PageNotAnInteger:
        posts=paginator.page(1)
    except EmptyPage:
        posts=paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})

def post_detail(request, year, month, day, post):
    post=get_object_or_404(Post, slug=post,
            status='published',
            publish__year=year,
            publish__month=month,
            publish__day=day)

    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            comment_form=CommentForm()
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments, 'comment_form': comment_form, 'similar_posts': similar_posts})

def post_share(request, post_id):
    post=get_object_or_404(Post, id=post_id, status='published')
    sent=False
    if request.method=='POST':
        form=EmailPostForm(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            posl_url=request.build_absolute_uri(post.get_absolut_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True

    else:
        form=EmailPostForm()
    return render(request, 'blog/post/share.html', {'post':post, 'form': form, 'sent':sent})

def post_search(request):
    form = SearchForm()
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            cd = form.cleaned_data
            results = SearchQuerySet().models(Post).filter(content=cd['query']).load_all()
            total_results = results.count()

        return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'cd': cd,
                   'results': results,                                                                                   'total_results': total_results})

    return render(request, 'blog/post/search.html', {'form': form})

blog/templates/blog/base.html
{# templates/blog/base.html #}

{% load staticfiles blog_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
<head>
	<!-- Meta tags -- >
	 <meta charset="utf-8">
	 <meta http-equiv="X-UA-Compatible" content="IE=edge">
	 <meta name="viewport" content="width=device-width,initial-scale=1">
	 <meta name="description" content="Blog for algerians">
	 <meta name="author" content="Achour Ait Hamiche">

    {# Title block #}
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'styles/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static 'styles/css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'styles/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>                                                                                                                                                                                                                          <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->                                              <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->                                                      <!--[if lt IE 9]>                                                                                                                   <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>                                                <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>      
    <![endif]-->
    <style>
.intro-header {
	background-image:url("{% static 'styles/img/home-bg.jpg' %}");
}
</style>
</head>
<body>
  <!-- Block header -->
  <div class="navbar navbar-default navbar-custom navbar-fixed-top">
	  <div class="container-fluid">
		  <div class="navbar-header page-scroll">
			  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				  <span class="sr-only">Toggle navigation</span>
				  Menu<i class="fa fa-bars"></i>
			</button>
			<a class="navbar-brand" href="/blog">BLOG OF DZ</a>
		  </div>
	
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
                <li class="" ><a href="{% url "blog:post_list" %}">Home</a></li>
                <li><a href="#">Contact</a></li>
                <li><a href="">About</a></li>
                <li><a href="{% url "blog:post_search" %}">SEARCH</a></li>
			</ul>
		</div>
	</div>
</div>

<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->                                                    


<header class="intro-header">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1"">
            <div class="site-heading">
                <h1 class="site-heading">Blog Of DZs</h1>
                <hr class="small">
                <span class="subheading">Your blog to know what matters</span>
            </div>
        </div>
    </div>
</header>

{# Content block #}
{% block content %}
{% endblock %}

<!-- Sidebar block -->
<div class="container">
    <div class="well text-center">
        <h2 class="page-header">Blog of DZs | 
            <small>
                <span class="badge"> {% total_posts %} posts</span> untill today
            </small>
        </h2>
        
        <div class="row">
            <div class="col-lg-6 col-md-6">
                <h3 class="page-header">Latest posts</h3>
                    {% get_latest_posts as latest_posts %}
                    <ul class="list-unstyled">
                        {% for post in latest_posts %}
                            <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
                        {% endfor %}
                    </ul>
            </div>

            <div class="col-lg-6 col-md-6">
		        <h3 class="page-header">Most commented posts</h3>
			        {% get_most_commented_posts as most_commented_posts %}
		            <ul class="list-unstyled">
			            {% for post in most_commented_posts %}
			                <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
		            {% endfor %}
		            </ul>
            </div>
        </div>
            <p class="lead">Don't want to miss updates!</p>
		    <button class="btn btn-default btn-lg"><a href="{% url "blog:post_feed" %}">Subscribe to RSS</a></button>
    </div>
</div>


<!-- Footer -->                                                                                                             
<footer>                                                                                                                            <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <ul class="list-inline text-center">                                                
                    
     <li>
         <a href="#"><span class="fa-stack fa-lg">
                 <i class="fa fa-circle fa-stack-2x"></i>
                 <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
             </span></a></li>                        
          <li>                                                                                                                                
        <a href="#">
            <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
            </span>
        </a>          <li>                                                                                                                                 <li>
                <a href="#">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                    </span>
                </a>
            </li>
            <ul>
                <p class="copyright text-muted">Copyright &copy; BlogOfDz 2017</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'styles/vendor/jquery/jquery.min.js' %}"></script>
    
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'styles/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'styles/js/clean-blog.min.js' %}"></script>
  </body>
</html>

blog/templates/blog/pagination.html
<div class="pagination">
	<ul class="pager">
	{% if page.has_previous %}
	<li class="previous"><a href="?page={{ page.previous_page_number }}">&larr; Previous</a></li>
    {% endif %}
  {% if page.has_next %}
	<li class="next"><a href="?page={{ page.next_page_number }}">Next &rarr;</a></li>
      {% endif %}
	</ul>
	  <span class="current">Page {{ page.number }} of {{ page.paginator.num_pages }}</span>
</div>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<article>
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-preview">
                    <h1 class="post-title">{{ post.title }} | <small class="badge">{{ comments.count }} comment{{ comments.count|pluralize }}</small></h1>
		            <p class="post-meta">Posted by {{ post.author }} on {{ post.publish }}</p>
		            {{ post.body|markdown }}
                    {# I will this section, link to share to facebook, twitter or by email #}
		            <p><a href="{% url "blog:post_share" post.id %}">Share this post</a></p>
                </div>
			</div>
		</div>
	</div>
</article>

<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
          <div class="panel panel-danger text-center">
            <h2>These similar posts may interest you</h2>   
                {% for post in similar_posts %}
                      <p><a class="text-danger" href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
                   {% empty %}
                       <p>There are no similar posts yet.</p>    
	             {% endfor %}
            </div>
        </div>
    </div>
</div>

<!-- Block Comments -->
<!-- Comments Form -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="well">
		        <h2>Leave a comment</h2>
		        <form action="." method="post" role="form">
                    <div class="form-group">
			    	    {{ comment_form|crispy }}
				        {% csrf_token %}
			            <button type="submit" class="btn btn-primary">Add a comment</button>
                    </div>
		        </form>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
         <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <h2 claiss="page-header">Comments | <small class="badge">{{ comments.count }} comment{{ comments.count|pluralize }}</small></h2>
                {% for comment in comments %}
                <div class="post-preview">
                    <p class="post-meta">Comment {{ forloop.count }} by <mark>{{ comment.name }}</mark> on {{ comment.created }}</p>
                </div>
                {{ comment.body|linebreaks }}
                    <hr/>
                {% empty %}
                    <h2 class="text-danger">There are no comments yet.</h2>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
	{% for post in latest_posts %}
	<li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
	{% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Blog of DZ{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

	{% if tag %}
        <h4>Post tagged with: "{{ tag.name }}"</h4>
    {% endif %}

			<div class="post-preview">
				{% for post in posts %}
					<a href="{{ post.get_absolute_url }}">
						<h2 class="post-title">{{ post.title }}</h2>
					</a>	
					<p class="post-meta">Published  by {{ post.author }} on {{ post.publish }}</p>
					<h3 class="post-subtitle">{{ post.body|markdown|truncatewords:30 }}</h3>

					<p>Tags:
    						{% for tag in post.tags.all %}
							<a class="text-danger" href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>
    							{% if not forloop.last %}, {% endif %}
						{% endfor %}
					</p>
					<hr/>
  				{% endfor %}
			</div>
	<!-- Pager -->
    		{% include "blog/pagination.html" with page=posts %}
		</div>
	</div>
</div>
{% endblock %}

blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% load blog_tags crispy_forms_tags %}

{% block title %}Search{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-2">
            <div class="panel panel-info">
                
                {% if "query" in request.GET %}
                <div class="panel-heading">
                    <h1 class="panel-title">Posts containing "{{ cd.query }}" | <small class="badge">{{ total_results }} result{{ total_results|pluralize }}</small></h1>
                </div>

                <div class="panel-body">
                    {% for result in results %}
                        {% with post=result.object %}
                        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                        {{ post.body|markdown|truncatewords_html:12 }}
                    {% endwith %}
                    {% empty %}
		                <h3>There are no results for your query.</3>
                    {% endfor %}
                    <button class="btn btn-default"><a class="text-danger" href="{% url "blog:post_search" %}">Search again</a></button>
                </div>
                {% else %}
                <div class="panel-heading">
                    <h1 class="panel-title">Search for posts</h1>
                </div>
                <div class="panel-body">
                    <form action="." method="get">
                        <div class="form-group">
                            {{ form|crispy }}
                            <button type="submit" class="btn btn-default">Search</divi>
                        </div>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post/share.html
{# templates/blog/post/share.html #}

{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Share a post{% endblock %}
 {% block content %}

<div class="container">
    <div class="row">
        <div class="well">
            {% if sent %}
            <h2 class="page-header">E-mail successfully sent</h2>
            <p class="text-success">"<mark>{{ post.title }}</mark>" was successfully sent to <mark>{{ cd.to }}</mark>.</p>
            {% else %}
                <h2 class="page-header">Share "{{ post.title }}" by e-mail</h2>
                     <form action="." method="post">
                        {{ form|crispy }}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">Send e-mail</button>
                    </form>
        </div>
    </div>
</div>
  {% endif %}
{% endblock %}